["Geography","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=001",1,0,0], 
["History: World","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=002",1,0,0], 
["History: United States","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=003",1,0,0], 
["Language and Literature","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=004",1,0,0], 
["Life Sciences","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=005",1,0,0], 
["Performing Arts","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=006",1,0,0], 
["Physical Sciences and Math","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=007",1,0,0], 
["Religion, Philosophy, Mythology","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=008",1,0,0], 
["Social Sciences","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=009",1,0,0], 
["Society and Government","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=010",1,0,0], 
["Sports, Games, Recreation","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=011",1,0,0], 
["Technology","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=012",1,0,0], 
["Visual Arts","/cgi-bin/subject_browse?templatename=/browse/browse.html&node=013",1,0,0], 
